seed: 0

dataloader:
    batch_size: 128
    num_workers: 4
    sampler: null  # ONLY FOR TRAIN SET: could be [null, rwy, rwg]

dataset:
    name: celeba
    root: ./data

    data_augmentation: false
    target_resolution: [224, 224]

    subgroup_labels: true
    groupings: [Blond_Hair:Male]

    ### these correspond directly to tasks specified in task labels, ensure they are either all 1 (no weighting) or sum up to 1 (weighting)
    task_weights: [1]
    loss_based_task_weighting: false 
    lbtw_alpha: 0.5

    ### subsampling/reweighting dataset
    subsample: false
    subsample_type: null

    cvx: null  # defaults to qp

model:
    name: resnet50
    pretrained: true
    num_classes: null  # should be len(config.dataset.groupings)

optimizer:
    name: sgd
    lr: 0.0001
    weight_decay: 0.0001 
    momentum: 0.9

train:
    n_gpus: 1
    total_epochs: 25
    load_ckpt: null
    ckpt_every_n_epochs: 1
    log_every_n_steps: 25
    eval_every_n_epochs: 1
    log_dir: ./logs/erm/Blond_Hair:Male
    grad_clip_norm: null
    ema: false
    fp16: true
    run_sanity_val_epoch: true

    # fields used by jtt, do not change for erm #
    up_type: null  # one of [upsample, upweight, null]
    lambda_up: 1
    load_up_pkl: null
    #############################################
