# Base name of config for each phase of ERM training
stage_1_config: jtt_stage_1
stage_2_config: jtt_stage_2

# Base log dir for both phases of ERM training
log_dir: &log_dir ./logs/jtt

task: 0

lambda_up: 50
load_stage_1_ckpt: null
load_upweight_pkl: null  # specify this to load it
load_stage_2_ckpt: null
