seed: 0

dataloader:
    batch_size: 128
    num_workers: 20

dataset:
    name: celeba
    root: ./data

    data_augmentation: false
    target_resolution: [224, 224]
    num_classes: &num_classes 1

    subgroup_labels: true

    ## GROUP 1
    task_labels: ["Blond_Hair"]
    subgroup_attributes: {
        "Blond_Hair": ["Male"]
    }

    ### these correspondd directly to tasks specified in task labels, ensure they are either all 1 (no weighting) or sum up to 1 (weighting)
    task_weights: [1]
    loss_based_task_weighting: false 
    lbtw_alpha: 0.5

model:
    name: resnet50
    pretrained: true
    num_classes: *num_classes
    num_tasks: 1

    # Defaults for ResNet
    zero_init_residual: False
    groups: 1
    width_per_group: 64
    replace_stride_with_dilation: null
    norm_layer: null

optimizer:
    name: sgd
    lr: 0.00001
    weight_decay: 0.1
    momentum: 0.9

train:
    n_gpus: 1
    total_epochs: 50
    load_ckpt: null
    ckpt_every_n_epochs: 1
    log_every_n_steps: 50
    eval_every_n_epochs: 1
    grad_clip_norm: null
    ema: false
    fp16: true

    # should only be overwritten from train_jtt #
    up_type: ???  # one of [upsample, upweight, null]
    lambda_up: ???  # this will control if the specified dataset should be upweighted for training
    load_up_pkl: ???
    log_dir: ???
    #############################################
