seed: 420

dataloader:
    batch_size: 128
    num_workers: 12

dataset:
    name: celeba
    root: ./data

    target_resolution: [224, 224]
    num_classes: &num_classes 1

model:
    name: resnet50
    pretrained: true
    num_classes: *num_classes

    # Defaults for ResNet
    zero_init_residual: False
    groups: 1
    width_per_group: 64
    replace_stride_with_dilation: null
    norm_layer: null

optimizer:
    name: sgd
    lr: 0.0001
    weight_decay: 0.0001
    momentum: 0.9

scheduler:
    name: linear
    warmup_steps: 1000

train:
    name: jtt
    lambda_up: 50

    n_gpus: -1
    total_steps: 31661  # ceil(202600 / 128) * 20 + 1
    load_ckpt: null
    ckpt_every_n_steps: 10000
    log_every_n_steps: 5
    eval_every_n_epochs: 1
    log_dir: ./logs/resnet50
    grad_clip_norm: null
    fp16: false
