seed: 420

dataloader:
    batch_size: 128
    num_workers: 8

dataset:
    name: celeba
    root: ./data

    target_resolution: [224, 224]
    num_classes: &num_classes 1

    subgroup_labels: true

    ## GROUP 1
    task_labels: ["Blond_Hair"]
    subgroup_attributes: {
        "Blond_Hair": ["Male"]
    }

    ## GROUP 2
    # task_labels: ["Pointy_Nose"]
    # subgroup_attributes: {
    #     "Pointy_Nose": ["Blond_Hair"]
    # }

    ## GROUP 3
    # task_labels: ["Bald"]
    # subgroup_attributes: {
    #     "Bald": ["Attractive"]
    # }

model:
    name: resnet50
    pretrained: true
    num_classes: *num_classes
    num_tasks: 1

    # Defaults for ResNet
    zero_init_residual: False
    groups: 1
    width_per_group: 64
    replace_stride_with_dilation: null
    norm_layer: null

optimizer:
    name: sgd
    lr: 0.0001
    weight_decay: 0.0001
    momentum: 0.9

train:
    name: jtt  # one of [erm, jtt]

    # jtt hyperparams
    lambda_up: 20
    stage_2_total_epochs: 20
    jtt_error_set: null
    # ###

    n_gpus: -1
    total_epochs: 1
    load_ckpt: null
    ckpt_every_n_epochs: 1
    log_every_n_steps: 5
    eval_every_n_epochs: 1
    log_dir: ./logs/jtt_subgroup_1
    grad_clip_norm: null
    fp16: true

test:
    load_ckpt: null
    results_dir: ./logs/jtt_subgroup_1/results
    size: 19962
