seed: 420

dataloader:
    batch_size: 64
    num_workers: 0

dataset:
    name: celeba
    root: ./data

    target_resolution: [224, 224]
    num_classes: &num_classes 40
    is_multiclass: &is_multiclass false

    task_labels: ["Blond_Hair"]
    subgroup_labels: True
    subgroup_attributes: {"Blond_Hair": ["Male"]} #mapping of task label to it's spurrious attributes

model:
    name: resnet50
    num_classes: *num_classes
    num_tasks: 2
    is_multiclass: *is_multiclass

    # Defaults for ResNet
    zero_init_residual: False
    groups: 1
    width_per_group: 64
    replace_stride_with_dilation: null
    norm_layer: null
    pretrained: true 

optimizer:
    name: sgd
    lr: 0.0001
    weight_decay: 0.0001
    momentum: 0.9

scheduler:
    name: linear
    warmup_steps: 1000

train:
    n_gpus: -1
    total_steps: 100000
    load_ckpt: null
    ckpt_every_n_steps: 10000
    log_every_n_steps: 5
    eval_every_n_epochs: 1
    log_dir: ./logs/resnet50
    grad_clip_norm: null
    fp16: true

test:
    load_ckpt: null
    results_dir: ./logs/
    size: 19962