# A default yaml that populates `exp` with per-experiment configs
defaults:
    - _self_
    - exp: suby
    - override hydra/job_logging: disabled
    - override hydra/hydra_logging: default

# Disable hydra creation of directories
hydra:
    output_subdir: null
    run:
        dir: .
